# Generated by Django 5.0.2 on 2024-02-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzntreeDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='available_stock_status',
            field=models.CharField(choices=[('H', 'High'), ('L', 'Low')], max_length=1),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='in_stock_status',
            field=models.CharField(choices=[('H', 'High'), ('L', 'Low')], max_length=1),
        ),
    ]
