# Generated by Django 5.0.2 on 2024-02-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kzntreeDashboard', '0002_alter_inventoryitem_available_stock_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='available_stock_status',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='in_stock_status',
        ),
    ]
