# Generated by Django 5.0.2 on 2024-02-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzntreeDashboard', '0004_builddashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builddashboard',
            name='completion_group_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
